// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-lT0mlEKj73KAy7iMeXp7A76sr2ZkBY',
    appId: '1:51597558416:web:b015f808382bba5b124e15',
    messagingSenderId: '51597558416',
    projectId: 'carnet-de-sante-9190a',
    authDomain: 'carnet-de-sante-9190a.firebaseapp.com',
    storageBucket: 'carnet-de-sante-9190a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3aqHm2ADRLbEudBRyGJwb5weB7I0O9A4',
    appId: '1:51597558416:android:1ab589bd20d0ffde124e15',
    messagingSenderId: '51597558416',
    projectId: 'carnet-de-sante-9190a',
    storageBucket: 'carnet-de-sante-9190a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cU3c-OCVhPpd7bC1MvV40Mu_FoW3HQc',
    appId: '1:51597558416:ios:35ea8095e9ddeede124e15',
    messagingSenderId: '51597558416',
    projectId: 'carnet-de-sante-9190a',
    storageBucket: 'carnet-de-sante-9190a.firebasestorage.app',
    iosClientId: '51597558416-dht55h4461sso792a93884278e5t13gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.carnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0cU3c-OCVhPpd7bC1MvV40Mu_FoW3HQc',
    appId: '1:51597558416:ios:35ea8095e9ddeede124e15',
    messagingSenderId: '51597558416',
    projectId: 'carnet-de-sante-9190a',
    storageBucket: 'carnet-de-sante-9190a.firebasestorage.app',
    iosClientId: '51597558416-dht55h4461sso792a93884278e5t13gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.carnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-lT0mlEKj73KAy7iMeXp7A76sr2ZkBY',
    appId: '1:51597558416:web:b9dffa6097ecaa32124e15',
    messagingSenderId: '51597558416',
    projectId: 'carnet-de-sante-9190a',
    authDomain: 'carnet-de-sante-9190a.firebaseapp.com',
    storageBucket: 'carnet-de-sante-9190a.firebasestorage.app',
  );
}
